# A Dockerfile must begin with a FROM instruction. This may be after parser directives, comments, and globally scoped ARGs.

# Arbitrary choose 17
FROM postgres:17


ENV POSTGRES_PASSWORD=psw
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=mydb

EXPOSE 5432